/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advancedsql;

import advancedsql.query.Create;
import org.junit.Test;

import java.sql.SQLException;
import java.util.HashMap;

import static org.junit.Assert.*;

public class MySQLTest {
    public MySQL connect() throws SQLException {
        return new MySQL("127.0.0.1", 3306, "root", "", "unittesting");
    }

    @Test public void testConnection() {
        try {
            MySQL mySQL = connect();

            assertTrue(mySQL.isConnected());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Test public void testCreateTable() {
        try {
            MySQL mySQL = connect();

            Create create = mySQL.table("test").create();

            create.id();

            create.string("first_name");

            create.string("last_name");

            System.out.println(create.toString());

            create.execute();

            assertTrue(mySQL.isConnected());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
