/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advancedsql;

import org.junit.Test;

import java.sql.SQLException;

import static org.junit.Assert.*;

public class MySQLTest {
    @Test public void testConnection() {
        try {
            MySQL mySQL = new MySQL("127.0.0.1", 3306, "root", "", "unittesting");

            assertTrue(mySQL.isConnected());
        } catch (SQLException e) {

        }
    }
}
